"""Baseline schema — creates every table from the current SQLAlchemy models.

For a brand-new database: ``alembic upgrade head``.
For a database that already has the tables (created earlier by
``Base.metadata.create_all``): ``alembic stamp head`` once, then use
autogenerated migrations from here on.

Revision ID: 0001_baseline
Revises:
Create Date: 2026-09-07
"""
from typing import Sequence, Union

from alembic import op

from app.database import Base
import app.models  # noqa: F401 — populate Base.metadata

revision: str = "0001_baseline"
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    Base.metadata.create_all(bind=op.get_bind())


def downgrade() -> None:
    Base.metadata.drop_all(bind=op.get_bind())
